-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local mainMod = "SUPER"

-- Launch terminal

-- Use xterm-256color for tmux on remote server

hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd("alacritty"))

-- Kill active window

hl.bind(mainMod .. " + Q", hl.dsp.window.close())

-- Toggle floating

hl.bind(mainMod .. " + F", hl.dsp.window.float({ action = "toggle" }))

-- Show application launcher

hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("pgrep -x wofi >/dev/null 2>&1 && killall wofi || wofi --dmenu --show drun"))

hl.bind(mainMod .. " + P", hl.dsp.window.pin())

-- Toggle split (dwindle)

hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))

hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("grim -g \"$(slurp -d)\" - | wl-copy"))

hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("hyprpicker --autocopy --format=hex"))

hl.bind("PRINT", hl.dsp.exec_cmd("grim -g $(slurp)-| swappy -f-"))

-- Clipboard

--bind = CTRL, C, exec, wl-copy

--bind = CTRL, V, exec, wl-paste

-- Cliphist

hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("cliphist list| wofi --dmenu| cliphist decode| wl-copy"))

-- Toggle window floating

hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.float({ action = "toggle" }))

-- Focus movement

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

-- Swap windows

hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.swap({ direction = "left" }))

hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.swap({ direction = "right" }))

hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.swap({ direction = "up" }))

hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.swap({ direction = "down" }))

-- Resize active window

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + Ctrl + left", hl.dsp.resizeactive(-60, 0))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + Ctrl + right", hl.dsp.resizeactive(60, 0))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + Ctrl + up", hl.dsp.resizeactive(0, -60))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + Ctrl + down", hl.dsp.resizeactive(0, 60))

-- Switch tpaces

hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 0 }))
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))

-- Move active window to workspace

hl.bind(mainMod .. " + SHIFT + " .. 1, hl.dsp.window.move({ workspace = 1 }, { follow = false }))

hl.bind(mainMod .. " + SHIFT + " .. 2, hl.dsp.window.move({ workspace = 2 }, { follow = false }))

hl.bind(mainMod .. " + SHIFT + " .. 3, hl.dsp.window.move({ workspace = 3 }, { follow = false }))

hl.bind(mainMod .. " + SHIFT + " .. 4, hl.dsp.window.move({ workspace = 4 }, { follow = false }))

hl.bind(mainMod .. " + SHIFT + " .. 5, hl.dsp.window.move({ workspace = 5 }, { follow = false }))

hl.bind(mainMod .. " + SHIFT + " .. 6, hl.dsp.window.move({ workspace = 6 }, { follow = false }))

hl.bind(mainMod .. " + SHIFT + " .. 7, hl.dsp.window.move({ workspace = 7 }, { follow = false }))

hl.bind(mainMod .. " + SHIFT + " .. 8, hl.dsp.window.move({ workspace = 8 }, { follow = false }))

hl.bind(mainMod .. " + SHIFT + " .. 9, hl.dsp.window.move({ workspace = 9 }, { follow = false }))

hl.bind(mainMod .. " + SHIFT + " .. 0, hl.dsp.window.move({ workspace = 10 }, { follow = false }))

-- Scrolling layout

hl.bind(mainMod .. " + T", hl.dsp.layout("move +col"))

hl.bind(mainMod .. " + R", hl.dsp.layout("move -col"))

hl.bind(mainMod .. " + SHIFT + T", hl.dsp.layout("swapcol r"))

hl.bind(mainMod .. " + SHIFT + R", hl.dsp.layout("swapcol l"))

hl.bind(mainMod .. " + G", hl.dsp.layout("fit active"))

hl.bind(mainMod .. " + H", hl.dsp.layout("colresize -0.05/"))

hl.bind(mainMod .. " + L", hl.dsp.layout("colresize +0.05"))

-- Workspace scroll

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Brightness controls

hl.bind(mainMod .. " + F3", hl.dsp.exec_cmd("brightnessctl -d*::kbd_backlight set +33%"))

hl.bind(mainMod .. " + F2", hl.dsp.exec_cmd("brightnessctl -d*::kbd_backlight set 33%-"))

-- Volume and media keys

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_SINK@ 10%+"))

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_SINK@ 10%-"))

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_SINK@ toggle"))

-- Brightness

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"))

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +5%"))

-- Moving/resizing windows

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + CTRL + left", hl.dsp.resizeactive("-10 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + CTRL + right", hl.dsp.resizeactive("10 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + CTRL + up", hl.dsp.resizeactive("0 -10"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + CTRL + down", hl.dsp.resizeactive("0 10"))

-- TODO: manual review (unknown dispatcher: moveactive)
-- hl.bind("$mainMod + left", hl.dsp.moveactive("-10 0"))

-- TODO: manual review (unknown dispatcher: moveactive)
-- hl.bind("$mainMod + right", hl.dsp.moveactive("10 0"))

-- TODO: manual review (unknown dispatcher: moveactive)
-- hl.bind("$mainMod + up", hl.dsp.moveactive("0 -10"))

-- TODO: manual review (unknown dispatcher: moveactive)
-- hl.bind("$mainMod + down", hl.dsp.moveactive("0 10"))

-- Scroll Overview toggle

hl.bind(mainMod .. " + O", function()
    if hl.plugin.scrolloverview ~= nil then
        hl.plugin.scrolloverview.overview("toggle")
    end
end)

-- === Quickshell ===

-- Restart quickshell

hl.bind(mainMod .. " + SHIFT + Z", hl.dsp.exec_cmd("pkill quickshell; quickshell -p ~/.config/mtsw-bar/src/shell.qml"))

-- Kill quickshell

hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("pkill quickshell"))
