-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- TODO: manual review: splash = false

-- Clipboard



hl.config({
    xwayland = {
        use_nearest_neighbor = false,
        force_zero_scaling = true,
    },
})

hl.config({
    debug = {
        disable_logs = false,
        enable_stdout_logs = true,
    },
})

-- General appearance and gaps

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 10,
        border_size = 1,
        layout = "scrolling",
    },
})

hl.config({
    decoration = {
        rounding = 10,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            range = 4,
            render_power = 3,
        },
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
})

hl.config({
    animations = {
        enabled = false,
    },
})


hl.config({
    dwindle = {
        preserve_split = true,
    },
})

hl.config({
    master = {
        new_status = "master",
    },
})

hl.config({
    scrolling = {
        column_width = 1,
        focus_fit_method = 0,
    },
})

hl.config({
    misc = {
        disable_splash_rendering = true,
        disable_hyprland_logo = true,
        force_default_wallpaper = -1,
    },
})

hl.config({
    input = {
        kb_layout = "us,ru",
        kb_options = "grp:win_space_toggle",
        follow_mouse = 1,
        touchpad = {
            natural_scroll = true,
        },
        sensitivity = 0,
    },
})

-- hl.window_rule({
--    name  = "float_on",
--    match = {
--        match = "title ^(Picture in picture)$",
--    },
--    -- TODO: review rule: "float on"})

--hl.window_rule({
--    name  = "pin_on",
--    match = {
--        match = "title ^(Picture in picture)$",
--    },
--    -- TODO: review rule: "pin on"
--})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)
