-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.env("GDK_BACKEND", "wayland,x11,*")

hl.env("XCURSOR_THEME", "Numix-Cursor")
hl.env("XCURSOR_SIZE", 24)

hl.env("QT_QPA_PLATFORM", "wayland")

hl.env("XDG_SCREENSHOTS_DIR", "~/screenshots")


